//
//  FPNOBJCCountryKey.swift
//  FlagPhoneNumber
//
//  Created by Aurelien on 20/05/2019.
//

import Foundation

@objc public enum FPNOBJCCountryKey: Int {
    case AF, ZA, AL, DZ, DE, AD, AO, AI, AG, SA, AR, AM, AW, AU, AT, AZ, BS, BH, BD, BB, BE, BZ, BM, BT, BY, BO, BA, BW, BN, BR, BG, BF, BI, BJ, KH, CM, CA, CV, CL, CN, CY, CO, KM, CG, CD, KP, KR, CR, HR, CU, CI, DK, DJ, DM, ES, EE, FJ, FI, FR, GA, GM, GH, GI, GD, GL, GR, GP, GU, GT, GG, GN, GQ, GW, GY, GF, GE, HT, HN, HK, HU, IN, ID, IQ, IR, IE, IS, IL, IT, JM, JP, JE, JO, KZ, KE, KG, KI, KW, RE, LA, LS, LV, LB, LY, LR, LI, LT, LU, MO, MK, MG, MY, MW, MV, ML, MT, MA, MQ, MU, MR, YT, MX, MD, MC, MN, MS, ME, MZ, MM, NA, NR, NI, NE, NG, NU, NO, NC, NZ, NP, OM, UG, UZ, PK, PW, PA, PG, PY, NL, PH, PL, PF, PR, PT, PE, QA, RO, GB, RU, RW, CF, DO, BL, KN, SM, MF, PM, VC, SH, LC, SV, WS, AS, ST, RS, SC, SL, SG, SK, SI, SO, SD, SS, LK, CH, SR, SE, SJ, SZ, SY, SN, TJ, TZ, TW, TD, CZ, IO, PS, TH, TL, TG, TK, TO, TT, TN, TM, TR, TV, UA, UY, VU, VE, VN, WF, YE, ZM, ZW, EG, AE, EC, ER, VA, FM, US, ET, CX, NF, IM, KY, CC, CK, FO, FK, MP, MH, SB, TC, VG, VI, AX
}

public let FPNOBJCCountryCode: [FPNOBJCCountryKey: String] = [
    .AF: "AF", .ZA: "ZA", .AL: "AL", .DZ: "DZ", .DE: "DE", .AD: "AD", .AO: "AO", .AI: "AI", .AG: "AG", .SA: "SA", .AR: "AR", .AM: "AM", .AW: "AW", .AU: "AU", .AT: "AT", .AZ: "AZ", .BS: "BS", .BH: "BH", .BD: "BD", .BB: "BB", .BE: "BE", .BZ: "BZ", .BM: "BM", .BT: "BT", .BY: "BY", .BO: "BO", .BA: "BA", .BW: "BW", .BN: "BN", .BR: "BR", .BG: "BG", .BF: "BF", .BI: "BI", .BJ: "BJ", .KH: "KH", .CM: "CM", .CA: "CA", .CV: "CV", .CL: "CL", .CN: "CN", .CY: "CY", .CO: "CO", .KM: "KM", .CG: "CG", .CD: "CD", .KP: "KP", .KR: "KR", .CR: "CR", .HR: "HR", .CU: "CU", .CI: "CI", .DK: "DK", .DJ: "DJ", .DM: "DM", .ES: "ES", .EE: "EE", .FJ: "FJ", .FI: "FI", .FR: "FR", .GA: "GA", .GM: "GM", .GH: "GH", .GI: "GI", .GD: "GD", .GL: "GL", .GR: "GR", .GP: "GP", .GU: "GU", .GT: "GT", .GG: "GG", .GN: "GN", .GQ: "GQ", .GW: "GW", .GY: "GY", .GF: "GF", .GE: "GE", .HT: "HT", .HN: "HN", .HK: "HK", .HU: "HU", .IN: "IN", .ID: "ID", .IQ: "IQ", .IR: "IR", .IE: "IE", .IS: "IS", .IL: "IL", .IT: "IT", .JM: "JM", .JP: "JP", .JE: "JE", .JO: "JO", .KZ: "KZ", .KE: "KE", .KG: "KG", .KI: "KI", .KW: "KW", .RE: "RE", .LA: "LA", .LS: "LS", .LV: "LV", .LB: "LB", .LY: "LY", .LR: "LR", .LI: "LI", .LT: "LT", .LU: "LU", .MO: "MO", .MK: "MK", .MG: "MG", .MY: "MY", .MW: "MW", .MV: "MV", .ML: "ML", .MT: "MT", .MA: "MA", .MQ: "MQ", .MU: "MU", .MR: "MR", .YT: "YT", .MX: "MX", .MD: "MD", .MC: "MC", .MN: "MN", .MS: "MS", .ME: "ME", .MZ: "MZ", .MM: "MM", .NA: "NA", .NR: "NR", .NI: "NI", .NE: "NE", .NG: "NG", .NU: "NU", .NO: "NO", .NC: "NC", .NZ: "NZ", .NP: "NP", .OM: "OM", .UG: "UG", .UZ: "UZ", .PK: "PK", .PW: "PW", .PA: "PA", .PG: "PG", .PY: "PY", .NL: "NL", .PH: "PH", .PL: "PL", .PF: "PF", .PR: "PR", .PT: "PT", .PE: "PE", .QA: "QA", .RO: "RO", .GB: "GB", .RU: "RU", .RW: "RW", .CF: "CF", .DO: "DO", .BL: "BL", .KN: "KN", .SM: "SM", .MF: "MF", .PM: "PM", .VC: "VC", .SH: "SH", .LC: "LC", .SV: "SV", .WS: "WS", .AS: "AS", .ST: "ST", .RS: "RS", .SC: "SC", .SL: "SL", .SG: "SG", .SK: "SK", .SI: "SI", .SO: "SO", .SD: "SD", .SS: "SS", .LK: "LK", .CH: "CH", .SR: "SR", .SE: "SE", .SJ: "SJ", .SZ: "SZ", .SY: "SY", .SN: "SN", .TJ: "TJ", .TZ: "TZ", .TW: "TW", .TD: "TD", .CZ: "CZ", .IO: "IO", .PS: "PS", .TH: "TH", .TL: "TL", .TG: "TG", .TK: "TK", .TO: "TO", .TT: "TT", .TN: "TN", .TM: "TM", .TR: "TR", .TV: "TV", .UA: "UA", .UY: "UY", .VU: "VU", .VE: "VE", .VN: "VN", .WF: "WF", .YE: "YE", .ZM: "ZM", .ZW: "ZW", .EG: "EG", .AE: "AE", .EC: "EC", .ER: "ER", .VA: "VA", .FM: "FM", .US: "US", .ET: "ET", .CX: "CX", .NF: "NF", .IM: "IM", .KY: "KY", .CC: "CC", .CK: "CK", .FO: "FO", .FK: "FK", .MP: "MP", .MH: "MH", .SB: "SB", .TC: "TC", .VG: "VG", .VI: "VI", .AX: "AX"
]
